### ISSUE TITLE
run each notebook in its direcory

### ISSUE THREAD

**Issue by Eloitor** [cvfosammmm/GSNB#19]
Is it possible to make each notebook run in its directory? This would allow to use relative imports.

This is my attempt https://github.com/cvfosammmm/Porto/pull/16

**Comment by Eloitor** [comment]
Can you test it? @cvfosammmm
It works for me...

I have two folders, 
in `folderA` I have `a.py` with `a=2` as its content.
in `folderB` I have `b.py` with  `b=2` as its content.
If I create two notebooks en each folder and import the respective `.py` file it works. 

I have tested this having the two notebooks opened on the same Porto instance. I also tested this in separate instances.

**Comment by cvfosammmm** [comment]
I just implemented the cwd change. You can see it in the latest commit.

**Comment by Eloitor** [comment]
Great! thank you
